version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  go: "1.25"

formatters:
  enable:
    - gofumpt
    - goimports
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/your-org/your-project) # Custom section for your local module

linters:
  enable:
    # Bugs & Performance
    - staticcheck
    - govet
    - unused
    - errcheck
    - ineffassign
    - bodyclose
    - noctx
    # Modernization
    - modernize
    - usetesting
    # Style & Complexity
    - revive
    - gocritic
    - prealloc
    - misspell
    # Security
    - gosec  
  settings:
    staticcheck:
      checks: ["all"]
    gosec:
      severity: medium
      confidence: medium

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
