// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fzdarsky/boardingpass/internal/command (interfaces: CommandExecutor)
//
// Generated by this command:
//
//	mockgen -destination=mock_executor.go -package=command github.com/fzdarsky/boardingpass/internal/command CommandExecutor
//

// Package command is a generated GoMock package.
package command

import (
	context "context"
	reflect "reflect"

	config "github.com/fzdarsky/boardingpass/internal/config"
	protocol "github.com/fzdarsky/boardingpass/pkg/protocol"
	gomock "go.uber.org/mock/gomock"
)

// MockCommandExecutor is a mock of CommandExecutor interface.
type MockCommandExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockCommandExecutorMockRecorder
	isgomock struct{}
}

// MockCommandExecutorMockRecorder is the mock recorder for MockCommandExecutor.
type MockCommandExecutorMockRecorder struct {
	mock *MockCommandExecutor
}

// NewMockCommandExecutor creates a new mock instance.
func NewMockCommandExecutor(ctrl *gomock.Controller) *MockCommandExecutor {
	mock := &MockCommandExecutor{ctrl: ctrl}
	mock.recorder = &MockCommandExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandExecutor) EXPECT() *MockCommandExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCommandExecutor) Execute(ctx context.Context, cmd *config.CommandDefinition, runUsingSudo bool) (*protocol.CommandResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, cmd, runUsingSudo)
	ret0, _ := ret[0].(*protocol.CommandResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCommandExecutorMockRecorder) Execute(ctx, cmd, runUsingSudo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCommandExecutor)(nil).Execute), ctx, cmd, runUsingSudo)
}
